intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

./: lib{cosy}: libul{cosy}: {hxx ixx txx cxx}{** -**.test... -version} \
  hxx{version} $impl_libs $intf_libs

# Unit tests.
#
exe{*.test}:
{
  test = true
  install = false
}

for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n}
  $d/exe{$n}: libul{cosy}: bin.whole = false
}

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCOSY_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCOSY_SHARED_BUILD

# Export options.
#
lib{cosy}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{cosy}: cxx.export.poptions += -DLIBCOSY_STATIC
libs{cosy}: cxx.export.poptions += -DLIBCOSY_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{cosy}: bin.lib.version = "-$version.project_id"
else
  lib{cosy}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcosy/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libcosy/
  install.subdirs = true
}
